sudo: required

env:
  - ARCH_TRAVIS_CLEAN_CHROOT=1

before_install:
  - sudo apt-get -qq update

install:
  - pip install ansible

arch:
  packages:
    - ansible
  script:
    - "cp inventory/hosts.example arch_desktop/inventory/hosts"
    - "cd arch_desktop; ansible-playbook full-desktop.yml --syntax-check"
    - "cd arch_desktop; sudo ansible-playbook full-desktop.yml -b"

script:
  - "ansible-playbook -i inventory/hosts.example --syntax-check jupyter-notebook/install-jupyter.yml"
  - "sudo ansible-playbook -i inventory/hosts.example jupyter-notebook/install-jupyter.yml"
  - "curl -s https://raw.githubusercontent.com/mikkeloscar/arch-travis/master/arch-travis.sh | bash"
