sudo: required

arch:
  packages:
    - ansible

script:
  - "curl -s https://raw.githubusercontent.com/mikkeloscar/arch-travis/master/arch-travis.sh | bash"
  - "cd arch-desktop; sudo ansible-playbook full-desktop.yml"
