sudo: required

env:
  - ARCH_TRAVIS_CLEAN_CHROOT=1

arch:
  packages:
    - ansible
  script:
    - "which python"
    - "mkdir arch_desktop/inventory/; echo localhost > arch_desktop/inventory/hosts"
    - "cd arch_desktop; ansible-playbook full-desktop.yml --syntax-check"
    - "cd arch_desktop; sudo ansible-playbook full-desktop.yml --connection=local -b"

script:
  - "curl -s https://raw.githubusercontent.com/mikkeloscar/arch-travis/master/arch-travis.sh | bash"
