sudo: required

env:
  - ARCH_TRAVIS_CLEAN_CHROOT=1

arch:
  packages:
    - ansible
  script:
    - "ls; ls /"
    - "cd arch-desktop; ansible-playbook full-desktop.yml --syntax-check"
    - "cd arch-desktop; sudo ansible-playbook full-desktop.yml --connection=local"

script:
  - "curl -s https://raw.githubusercontent.com/mikkeloscar/arch-travis/master/arch-travis.sh | bash"
