sudo: required

env:
  - ARCH_TRAVIS_CLEAN_CHROOT=1

dist: trusty

before_install:
  - sudo apt-get -qq update

install:
  - sudo pip install ansible

arch:
  packages:
    - ansible
  script:
    - "ansible-playbook -i inventory/hosts.example arch_desktop/full-desktop.yml --syntax-check"
    - "sudo ansible-playbook -i inventory/hosts.example arch_desktop/full-desktop.yml"
    - "ansible-playbook -i inventory/hosts.example octoprint_setup/octoprint_setup.yml --syntax-check"
    - "sudo ansible-playbook -i inventory/hosts.example octoprint_setup/octoprint_setup.yml"

script:
  - "ansible-playbook -i inventory/hosts.example --syntax-check jupyter-notebook/install-jupyter.yml"
  - "sudo ansible-playbook -i inventory/hosts.example jupyter-notebook/install-jupyter.yml"
  - "ansible-playbook -i inventory/hosts.example --syntax-check phant.io/install-phant.yml"
  - "sudo ansible-playbook -i inventory/hosts.example phant.io/install-phant.yml"
  - "curl -s https://raw.githubusercontent.com/mikkeloscar/arch-travis/master/arch-travis.sh | bash"
