sudo: required

env:
  - ARCH_TRAVIS_CLEAN_CHROOT=1

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y ansible

arch:
  packages:
    - ansible
  script:
    - "cp inventory/hosts.example arch_desktop/inventory/hosts"
    - "cd arch_desktop; ansible-playbook full-desktop.yml --syntax-check"
    - "cd arch_desktop; sudo ansible-playbook full-desktop.yml -b"

script:
  - "cp inventory/hosts.example jupyter-notebook/inventory/hosts"
  - "cat jupyter-notebook/inventory/hosts"
  - "( cd jupyter-notebook; ansible-playbook --syntax-check install-jupyter.yml )"
  - "( cd jupyter-notebook; sudo ansible-playbook install-jupyter.yml )"
  - "curl -s https://raw.githubusercontent.com/mikkeloscar/arch-travis/master/arch-travis.sh | bash"
