---
- name: Configuracion basica de un Arch para Pi
  hosts: all
  vars:
    octo_path: "{{ ansible_env.HOME }}/Octoprint-git"
  tasks:
    - pacman:
        name: "{{ item }}"
        state: installed
      with_items:
        - git
        - vim
        - sudo
        - screen
        - python2-virtualenv
      become: yes
    - name: Descarga octoprint
      git:
        repo: https://github.com/foosel/OctoPrint.git
        dest: "{{ octo_path }}"
    - command: /usr/bin/virtualenv2 {{ octo_path }}/venv chdir={{ octo_path }}
    - command: ./venv/bin/python setup.py install chdir={{ octo_path }}
