---
- name: Install the AUR packages remaining for full desktop
  hosts: all
  tasks:
    - include_vars: vars/package-list.yml
    - name: Upgrades packages and pacman repo
      pacman: update_cache=yes 
      become: yes
    - name: Installs packages from AUR using pacaur
      aur:
        name: "{{ item }}"
        user: alvaro
      with_flattened:
        "{{ packages_aur }}"
