---
- name: Install the AUR packages remaining for full desktop
  hosts: all
  tasks:
    - name: Upgrades packages and pacman repo
      pacman: update_cache=yes 
      become: yes
    - name: Installs packages from AUR using pacaur
      aur:
        name: "{{ item }}"
        user: alvaro
      with_items:
        - fritzing
        - xflux
        - package-query
        - yaourt
        - hamlib
        - grig
        - gpredict
        - xflux-gui-git
