---
- name: Install a full arch linux desktop
  hosts: all
  tasks:
    - name: Upgrades packages and pacman repo
      pacman: update_cache=yes upgrade=yes
      become: yes
    - name: Installs packages for a "full" desktop
      pacman: name={{ item }} state=present
      with_items:
        - ansible
        - arduino-avr-core
        - atom
        - audacity
        - base-devel
        - celestia
        - cheese
        - chromium
        - clementine
        - firefox
        - freecad
        - gimp
        - git
        - gnome-calculator
        - gnome-terminal
        - gthumb
        - guvcview
        - inkscape
        - k3b
        - kdegraphics-okular
        - klavaro
        - kodi
        - ktorrent
        - libappindicator-gtk3
        - libreoffice
        - lightdm 
        - lxc
        - mono
        - mpv
        - mtr
        - obs-studio
        - openshot
        - pidgin
        - processing
        - pwgen
        - rsync
        - screen
        - soundconverter
        - stellarium
        - tcpdump
        - thunderbird
        - unzip
        - vim
        - virt-manager
        - vlc
        - wget
        - wireshark-gtk
        - xorg-server
        - youtube-dl
      become: yes
