---
- name: Install a full arch linux desktop
  hosts: all
  tasks:
    - name: Upgrades packages and pacman repo
      pacman: update_cache=yes upgrade=yes
      become: yes
    - name: Installs packages for a "full" desktop
      pacman: name={{ item }} state=present
      with_items:
        - lightdm 
        - freecad
        - libreoffice
        - firefox
        - thunderbird
        - inkscape
        - gimp
        - pidgin
        - ktorrent
        - clementine
        - celestia
        - chromium
        - kdegraphics-okular
        - k3b
        - audacity
        - tcpdump
        - wireshark-gtk
        - gthumb
        - mpv
        - vlc
        - processing
        - atom
        - virt-manager
        - openshot
        - xorg-server
        - git
        - cheese
        - guvcview
        - kodi
        - obs-studio
        - klavaro
        - stellarium
        - base-devel
        - gnome-terminal
        - soundconverter
        - rsync
      become: yes

