---
- name: Install a full arch linux desktop
  hosts: all
  tasks:
    - name: Upgrades packages and pacman repo
      pacman: update_cache=yes upgrade=yes
      become: yes
    - name: Installs packages for a "full" desktop
      pacman: name={{ item }} state=present
      with_items:
        - ansible
        - arduino
        - arduino-avr-core
        - atom
        - audacity
        - base-devel
        - celestia
        - cheese
        - chromium
        - clementine
        - firefox
        - freecad
        - gimp
        - git
        - gnome-calculator
        - gnome-screenshot
        - gnome-terminal
        - gthumb
        - guvcview
        - inkscape
        - k3b
        - okular
        - klavaro
        - kodi
        - ktorrent
        - libappindicator-gtk3
        - libreoffice
        - lightdm 
        - lxc
        - networkmanager
        - mksyslinux
        - mono
        - mpv
        - mtr
        - obs-studio
        - openshot
        - pidgin
        - processing
        - python-pip
        - python2-pip
        - pwgen
        - rsync
        - screen
        - soundconverter
        - stellarium
        - strace
        - syslinux
        - tcpdump
        - thunderbird
        - unzip
        - vim
        - virt-manager
        - vlc
        - wget
        - wireshark-gtk
        - xorg-server
        - youtube-dl
      become: yes
    - name: Installs python2 modules
      pip:
        name: "{{ item }}"
        executable: pip2
        state: latest
      with_items:
        - jsonmerge
        - json-spec
        - esptool
      become: yes
    - name: Installs python3 modules
      pip:
        name: jsonmerge
        executable: pip3
        state: latest
      become: yes
    - name: Starts and enable services
      service:
        name: "{{ item }}"
        enabled: yes
        state: started
      with_items:
        - NetworkManager
      become: yes
      ignore_errors: true
