---
- name: Install a full arch linux desktop
  hosts: all
  tasks:
    - name: Upgrades packages and pacman repo
      pacman: update_cache=yes upgrade=yes
      become: yes
    - name: Installs packages for a "full" desktop
      pacman: name={{ item }} state=present
      with_items:
        - ansible
        - arduino
        - arduino-avr-core
        - atom
        - audacity
        - base-devel
        - bind-tools
        - cdrdao
        - celestia
        - cheese
        - chromium
        - cinnamon
        - cinnamon-screensaver
        - clementine
        - cool-retro-term
        - cuda
        - cups
        - debootstrap
        - dia
        - dkms
        - dmidecode
        - dvd+rw-tools
        - firefox
        - freecad
        - gimp
        - git
        - gnome-calculator
        - gnome-screenshot
        - gnome-terminal
        - gtk3-print-backends
        - gthumb
        - guvcview
        - hplip
        - inkscape
        - ipcalc
        - iptraf-ng
        - isomd5sum
        - k3b
        - kicad
        - kteatime
        - okular
        - klavaro
        - kodi
        - ktorrent
        - libappindicator-gtk3
        - libreoffice-fresh
        - lightdm
        - lshw
        - lsof
        - lxc
        - networkmanager
        - mksyslinux
        - mono
        - mpv
        - mtr
        - obs-studio
        - openshot
        - pidgin
        - processing
        - python-pip
        - python-setproctitle
        - python2-pip
        - pv
        - pwgen
        - rsync
        - rpmextract
        - sane
        - screen
        - simple-scan
        - soundconverter
        - stellarium
        - strace
        - syslinux
        - system-config-printer
        - openssh
        - tcpdump
        - thunderbird
        - unzip
        - vim
        - virt-manager
        - vlc
        - wget
        - wireshark-gtk
        - xorg-server
        - youtube-dl
      become: yes
    - name: Installs python2 modules
      pip:
        name: "{{ item }}"
        executable: pip2
        state: latest
      with_items:
        - jsonmerge
        - json-spec
        - esptool
      become: yes
    - name: Installs python3 modules
      pip:
        name: "{{ item }}"
        executable: pip3
        state: latest
      with_items:
        - jsonmerge
        - droopescan
        - adafruit-ampy
      become: yes
    - name: Starts and enable services
      service:
        name: "{{ item }}"
        enabled: yes
        state: started
      with_items:
        - NetworkManager
        - org.cups.cupsd.service
      become: yes
      ignore_errors: true
    - name: Disables systemd-coredump (creates dir)
      file: path=/etc/systemd/coredump.conf.d/ state=directory mode=0755
      become: yes
    - name: Disables systemd-coredump (creates conf file)
      copy:
        dest: /etc/systemd/coredump.conf.d/disable.conf
        content: |
          [Coredump]
          Storage=none
      become: yes
    - name: Deshabilita biosdevname
      lineinfile:
        regexp: '^GRUB_CMDLINE_LINUX=""'
        dest: "/etc/default/grub"
        line: 'GRUB_CMDLINE_LINUX="net.ifnames=0 biosdevname=0"'
        state: present
        backrefs: yes
      ignore_errors: true
      become: yes
      register: grub_default_biosdevname
    - name: Actualiza grub luego de deshabilitar biosdevname 
      command: grub-mkconfig -o /boot/grub/grub.cfg
      ignore_errors: true
      become: yes
      when: grub_default_biosdevname.changed
    - name: Crea usuario alvaro
      user:
        name: alvaro
        groups: wheel,uucp,sys
        append: yes
        comment: Conde
      become: yes
    - name: Configuracion para sudo desde grupo wheel
      copy:
        dest: /etc/sudoers.d/wheel.conf
        content: '%wheel ALL=(ALL) ALL'
        validate: 'visudo -cf %s'
      become: yes
