---
- name: Install a full arch linux desktop
  hosts: all
  tasks:
    - name: Disables systemd-coredump (creates dir)
      file: path=/etc/systemd/coredump.conf.d/ state=directory mode=0755
      become: yes
    - name: Disables systemd-coredump (creates conf file)
      copy:
        dest: /etc/systemd/coredump.conf.d/disable.conf
        content: |
          [Coredump]
          Storage=none
      become: yes
    - name: Deshabilita servicio de systemd-coredump
      service:
        name: systemd-coredump.socket
        enabled: no
        state: stopped
      become: yes
    - name: Deshabilita biosdevname
      lineinfile:
        regexp: '^GRUB_CMDLINE_LINUX=""'
        dest: "/etc/default/grub"
        line: 'GRUB_CMDLINE_LINUX="net.ifnames=0 biosdevname=0"'
        state: present
        backrefs: yes
      ignore_errors: true
      become: yes
      register: grub_default_biosdevname
    - name: Actualiza grub luego de deshabilitar biosdevname 
      command: grub-mkconfig -o /boot/grub/grub.cfg
      ignore_errors: true
      become: yes
      when: grub_default_biosdevname.changed
    - name: Crea usuario alvaro
      user:
        name: alvaro
        groups: wheel,uucp,sys
        append: yes
        comment: Conde
      become: yes
    - name: Configuracion para sudo desde grupo wheel
      copy:
        dest: /etc/sudoers.d/wheel.conf
        content: '%wheel ALL=(ALL) ALL'
        validate: 'visudo -cf %s'
      become: yes
